### ISSUE TITLE
Exporting to PowerBI format very slow

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#132]
The `create_BI_format_file()` function took 4 hours to export the data. As a point of reference, running the model took ~3mins.

@Rosejoycrocker please put this at the very bottom of your priorities but when you get the chance it would be great if the data aggregation process could be vectorized.

EDIT: Should mention this was for a 2,568 scenario dataset

**Comment by Rosejoycrocker** [comment]
Do you reckon this is no longer relevant @ConnectedSystems ?

**Comment by ConnectedSystems** [comment]
Agree. Please also remove the corresponding methods too then
