### ISSUE TITLE
Use measure of dhw time distribution for MCDA heat stress criteria

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#151]
- currently ADRIA uses the current time step of dhw to measure heat stress suitability of a site for selecting sites for seeding and shading.l
- propose to change this to reflect furture rise in dhws as well as frequency of dhws, such as through median and max value over time.

**Comment by ConnectedSystems** [comment]
Hi Rose, on closing an issue it's best to state "why" for posterity.

e.g., was this addressed by a recent PR or commit? If so, what was its ID?
Is this no longer relevant? If so, state why.

**Comment by Rosejoycrocker** [comment]
Closed as discussions with Ken Anthony suggested it was not a priority for now.

**Comment by ConnectedSystems** [comment]
"Not a priority" in the sense of "we're not going to do this" or "it's not a focus right now" ?

If the latter, you don't need to close it - just leave it open until we get around to it.
