### ISSUE TITLE
Update site_selection() function in Domain.jl and use within ADRIA model site selection process to reduce replication

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#194]
- site_selection() function in Domain.jl has not been updated to match new structures, such as dmca_vars
- also, site_selection replicates a lot of code which is used in the site selection process in ADRIA, so this code should be unified to avoid replication

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker is this issue now resolved?

**Comment by Rosejoycrocker** [comment]
Not yet, the site_selection function is updated but not yet fully used within the ecological model. I planned to do this in a different PR so there weren't too many changes in one PR. This will included using the new MCDA_vars construction function in scenario.jl etc

**Comment by Rosejoycrocker** [comment]
I think this is actualloy resolved now actually, sorry. Other changes can be made through the 'make MCDA more generic' issue
