### ISSUE TITLE
Use NamedDims+AxisKeys instead of matrix for MCDA decision matrices

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#221]
- currently decision matrices for the MCDA are of type Matrix, open to the risk of mistaking the criteria type for each column.
- type should be changed to NamedArray so that the criteria type is easily identified and bugs are less likely to be introduced with changes to criteria etc.

**Comment by ConnectedSystems** [comment]
As in #200 - standardize to NamedDimsArray + AxisKeys instead of NamedArrays.

We'll need to have #247 merged before we tackle this
