### ISSUE TITLE
Use mean distance threshold and change in aggregate criteria value threshold instead of site by site distance threshold and top_n in distance sorting

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#237]
- currently the distance sorting algorithm sorts through the top n ranked sites to find suitable sites to replace sites which are too close together (as defined by the distance threshold).
- it was found that when these alternative sites have too much difference between higher ranked sites in their aggregate criteria they produce poorer results than not using the distance metric.
- instead of searching through the top n ranked sites, the number of sites to search through would be set by a maximum change between ranks in aggregate criteria value, to avoid too low value sites being selected.
- the average distance over sites could also be used to compare to the threshold distance, so that some high value sites can be close together, so long as the avergae ditance is sufficiently high. This avoids an issue identified in which high value sites may be discarded if several are very close together.

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker is this still relevant/active?

**Comment by Rosejoycrocker** [comment]
> @Rosejoycrocker is this still relevant/active?

Probably not relevant anymore following our conversations on using spatial clustering to sort sites
