### ISSUE TITLE
Adjust definition or sampling of dist_thresh so that the value representing 'don't use distance sorting' is as likely as values representing using distance sorting

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#238]
- currently, distance sorting is not used in site selection if dist_thresh = 1.0, but this value is unlikely to occur with current sampling settings.
- the definition of dist_thresh or its sampling should be adjusted so that there is not a bias towards using the distance sorting algorithm in the sampling.

**Comment by ConnectedSystems** [comment]
I've decided the best course of action here is to use a separate factor to indicate whether the distance sorting is "active" or "inactive". Please treat this as a priority for v0.4.6

**Comment by Rosejoycrocker** [comment]
Ok cool, I'll make this a priority
