### ISSUE TITLE
Investigate bounds used for coral_cover_tol

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#239]
- results in November deliverable report suggest bounds may not be stringent enough as siteswith quite low k are still being selected.
- maybe compare efficacy of using k area alone versus k area remaining.

**Comment by ConnectedSystems** [comment]
You may want to redo some of the analysis given the change in #276

**Comment by Rosejoycrocker** [comment]
Good point, sorry there's a couple of issues I need to get onto

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker  Is this complete? If so, could a summary be provided and the issue closed? Thank you

**Comment by Rosejoycrocker** [comment]
Use of k area as a criteria has been superceded by use of k area remaining for corals to be planted on. Sites of low k being selected is no longer such an issue as using k area remaining reflects the true available area for corals to be planted, not the potential realestate at the initial time the simulation begins. Coral_cover_tol has also been changed to express the proportion of area to be seeded which should be available at a site if planting is considered, which is a more intuitive input than the proportion it previously represented.
