### ISSUE TITLE
Set up documentation system and website

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#240]
Use the Documenter.jl system

https://documenter.juliadocs.org/stable/

**Comment by Rosejoycrocker** [comment]
Thanks Takuya, I'll have a look

**Comment by Rosejoycrocker** [comment]
Hey Takuya, I've started adding some documentation but I realised maybe it's too detailed. I was going to put an intro in the MCDA section which explains the decision matrix set up and MCDA approach before some MCDA examples - is that ok?

**Comment by ConnectedSystems** [comment]
Hi Rose,

I made an empty file for MCDA (linked below). Feel free to fill that with as much as you want.
Generally I would give a brief overview at the top with all the detail in later sub-sections so readers can choose to leave when they've feel like they got enough context.

https://github.com/open-AIMS/ADRIA.jl/blob/cd704e983e22a91dd76eb3d18a47c806cf3447fc/docs/src/dMCDA.md

**Comment by Rosejoycrocker** [comment]
Ok cool, thanks :)

**Comment by Rosejoycrocker** [comment]
I'm going to work a bit on the synthetic data repo I've set up this morning but then I'll do some work on documentation

**Comment by ConnectedSystems** [comment]
Documentation system setup from commit f920165365ccf2ed10d3a10ffebec435e47c9c46 and beyond and the GitHub Pages site is up and running, so I am closing this issue.
