### ISSUE TITLE
Possible bug in `site_selection`

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#284]
When running `site_selection` across multiple scenarios, it appears the wave scenario ID is used to select from both wave and DHW data cubes:

https://github.com/open-AIMS/ADRIA.jl/blob/0b14273264cb95df2d5c59cccf6097e3dda1d03c/src/sites/dMCDA.jl#L790

```
wave_scens[timestep, :, criteria.wave_scenario[cover_ind]],
dhw_scens[timestep, :, criteria.wave_scenario[cover_ind]],
```

Is this intended @Rosejoycrocker ? If so, does this mean Wave and DHW scenarios are tied together?

**Comment by Rosejoycrocker** [comment]
This was not intended, I thought I had fixed this but somehow it was not pushed. It should be 
``dhw_scens[timestep, :, criteria.dhw_scenario[cover_ind]]``

**Comment by Rosejoycrocker** [comment]
Thanks for spotting, sorry it was missed

**Comment by ConnectedSystems** [comment]
Just checking - I'll fix it in my set of changes to remove NamedArrays

**Comment by Rosejoycrocker** [comment]
Thanks!
