### ISSUE TITLE
Investigate alternative method for sampling mcda weights 

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#327]
Currently, the weightings for mcda criteria are sampled using uniform distributions for each of the individual weights. 
As the weights are then normalised for each intervention (e.g. all the seeding weights are normalised so that their sum is equal to one etc.), there is a bias away from extreme weighting combinations (values close to 1 or 0). This issue proposes looking into alternative methods for sampling the weights which do not bias the sample towards mid-range values.

Uncertainty in MCDA weights is generally tackled via expert elicitation, but there are difficulties with this including issues with the methods used for expert elicitation and difficulties with accessing experts for every decision instance.  To counter this, the area of Stochastic Multicriteria Acceptibility Analysis (SMAA) has develped methods for understanding the impact of uncertainty in MCDA weights and the criteria selection on decision outcomes (Pelissari et. al. 2020). Implementation of SMAA methods would require considerable retructuring of the current codebase, but this area may be useful in understanding methods for sampling the criteria weightings without bias. Studies in this area use techniques for sampling finite convex polytopes under known linear constraints. In this case the convex polytope is the n-dimensional weights space $W$ which encompasses all possible combinations of n criteria weightings under the constraint that $\sum{w_i}=1$ $\forall (w_1,...,w_n)\in W$. The common method used for sampling finitre convex polytopes under a known linear constraint is to use a Dirichlet distribution with concentration parameters $\alpha_i=1$  $\forall i=1,...,n$. Sampling from this distribution gives a vector of length $n$ where each element $w_i \in [0,1]$ is drawn from a uniform distribution and the vector of $w_i$'s sums to one. Sampling from a Dirichlet distribution for each set of weights (for each intervention) will give a weights vector which already sums to one, so it will not be skewed by normalisation later on in the mcda process. 

In the current definition of the weights, however, each weights parameter must be associated with a single distribution and set of bounds for that distribution. Switching to a Dirichlet distribution for each set of weights would require associating each set of intervention weights with a single distribution, which could destroy the Sobol sampling scheme. Whether this can be implemented without disrupting the current scheme needs to be investigated and if it does destroy the sampling scheme, what are the alternatives?

[1] Pelissari, R., Oliveira, M.C., Amor, S.B. et al. SMAA methods and their applications: a literature review and future research directions. Ann Oper Res 293, 433–493 (2020). https://doi.org/10.1007/s10479-019-03151-z

**Comment by ConnectedSystems** [comment]
Hi Rose,

I mentioned at one point that other MCDA approaches adopt alternate normalisation approaches to deal with this issue of biased weight values.

Could you look at those in the first instance before alternate sampling methods?

Rank normalisation and vector normalisation look promising.

**Comment by ConnectedSystems** [comment]
Is this still relevant Rose? If not, please close.

**Comment by Rosejoycrocker** [comment]
I think it's still relevant- the range of values when normalised is still lacking in extremes (0 and 1). Sorry I think I was looking into this when we got distracted by that error in the ODE a while ago. I can look into it again. I think the rank normalisation looked promising.

**Comment by ConnectedSystems** [comment]
As discussed, no longer relevant due to planned improvements and performance assessment.
