### ISSUE TITLE
MCDA crashes with mismatched array sizes for `rankings` and `rankingsin`

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#333]
Raises "could not be broadcast to match destination" (or similar - error message got cut off).

Error is raised [here](https://github.com/open-AIMS/ADRIA.jl/blob/088f99334d6dcbb6ace85834b25fb4ebd4802c98/src/sites/dMCDA.jl#L520-L523), but is caused by `rankingsin` having only two entries to fill `rankings` which has > 2 elements.

This occurs on the `centrality-calc-#329` branch (https://github.com/open-AIMS/ADRIA.jl/tree/centrality-calc-%23329)

MWE to reproduce error:

```julia
using Revise, Infiltrator
using ADRIA, Aviz


dom = ADRIA.load_domain("path to domain")

ADRIA.fix_factor!(dom;
    guided=3,  # Only use VIKOR
    seed_TA=Int64(5e5),  # Always seed (half million each enhanced species)
    seed_CA=Int64(5e5),
    use_dist=1,    # Spread locations around as much as possible
    top_n=30,
    dist_thresh=0.1,
    in_seed_connectivity=0.2,
    out_seed_connectivity=1.0,
    heat_stress=0.8,
    wave_stress=0.5,
    deployed_coral_risk_tol=1.0
)

scens = ADRIA.sample(dom, 1024)

rs = ADRIA.run_scenarios(scens, dom, "45")
```

**Comment by ConnectedSystems** [comment]
Note, I've found fixing `deployed_coral_risk_tol` to `1.0` is necessary. 

Anything lower seems to mess with the rankings too much, and may even remove all locations from consideration. This may be why unguided may outperform guided scenarios (e.g., there are "guided" scenarios where no interventions were deployed).

**Comment by Rosejoycrocker** [comment]
Thanks for picking this up, I'll have a look this afternoon.

**Comment by Rosejoycrocker** [comment]
Hey @ConnectedSystems, having a preliminary look into this rn and by 
>Anything lower seems to mess with the rankings too much, and may even remove all locations from consideration. This may be why unguided may outperform guided scenarios (e.g., there are "guided" scenarios where no interventions were deployed).

do you mean the fact that you tend to get only 30-50 sites to choose from as opposed to the 136 when the risk_tol is set to 1.0?

**Comment by Rosejoycrocker** [comment]
I think I've found the source of the issue. It seems to occur when rankingsin gets so small that it only has site ids which are in prefseedsites and prefshadesites. This means that when the set of available sites are filtered so that only previously unused sites are considered, the set is empty. This doesn't happen when deployed_coral_risk_tol = 1.0, because no heat and wave stress filtering occurs and so there are always enough sites to not reuse sites.

Given this and our conversation about the risk tolerance, do we alter the range of values the risk tolerance can have, get rid of it entirely, or make the default be no risk filtering?...

**Comment by ConnectedSystems** [comment]
My preference is to get rid of it. Collapses a dimension and better aligns with the conditions you mentioned re MCDA methods work best with independent criteria.

Does raise the question of what to do when the set is empty under different circumstances (e.g., all locations are too hot).
I'd say delay deployments for that year.

Later we need a more flexible dynamic option. Something like deploy so long as good conditions are detected, and there hasn't been a recent deployment.

**Comment by Rosejoycrocker** [comment]
>My preference is to get rid of it. Collapses a dimension and better aligns with the conditions you mentioned re MCDA methods work best with independent criteria.

Ok cool, I agree. I'll also get rid of it in the make-mcda-generic PR. Do we then get rid of filtering entirely (as in get rid of the space for planted corals filter also)? This would simplify some things in the PR also.

>Does raise the question of what to do when the set is empty under different circumstances (e.g., all locations are too hot).
I'd say delay deployments for that year.

How else do we know all the locations are too hot though other than a filter? The filter tells us the sites are above a threshold in terms of heat stress...

**Comment by ConnectedSystems** [comment]
> How else do we know all the locations are too hot though other than a filter?

Does this mean setting a high heat stress criteria does not rank locations so low that they become effectively removed from further consideration?

**Comment by Rosejoycrocker** [comment]
>For now, I'd only get rid of it if we already have a criterion that speaks to available area as well. e.g., how willing are we to inefficiently stuff a location with extra coral, relative to available space. If we don't have such a criterion, I think it's a sensible pre-filtering to do at least for now.

We do have an available space criteria, I think the filtering was brought in because we were finding sites were still being selected with little space if they did really well in terms of heat/ wave stress.  But you're right, this filtering is more about efficiency from the perspective of planting corals, so makes sense to keep it.

**Comment by Rosejoycrocker** [comment]
This is normalization for the criteria not the weighting? This definitely sounds like a better normalization than min-max if so, but I don't see how they are removed from selection. If all the values are verry low, all the sites will be seen as equivalent in terms of heat stress and so the selection will be dependent on other criteria.

**Comment by Rosejoycrocker** [comment]
Ah I think I see. So have `risk_tol` as a non-varying low value so that anything with $x$ close to $\phi$ is filtered out?

**Comment by ConnectedSystems** [comment]
Yeah, but hold off on that for now. I had a play around with it yesterday but there seems to be something else going on because the outcomes are pretty much the same.

**Comment by Rosejoycrocker** [comment]
hmm ok... what valuies did you use for $c$ and $\phi$?

**Comment by ConnectedSystems** [comment]
I just used max scaling as I realised the approach above would be weird under "usual" conditions (max DHW of 5, for example).

$x$ was set to 20, an arbitrary value for now.

**Comment by Rosejoycrocker** [comment]
So you used min-max normalisation with the max=20?

**Comment by ConnectedSystems** [comment]
No, max scaling, or max normalisation:

$x / max(x)$ where $x$ is a vector or matrix

**Comment by Rosejoycrocker** [comment]
Right and what was the non-varying threshold you used?

**Comment by ConnectedSystems** [comment]
See edits above - sorry wrote it out in a rush

**Comment by Rosejoycrocker** [comment]
Thanks, sorry one last question- this was with filtering disabled (like risk_tol=1.0)?

**Comment by ConnectedSystems** [comment]
Yes ma'am!

**Comment by Rosejoycrocker** [comment]
Thanks, looking into it. Seems like a weirder bug than I thought...

**Comment by Rosejoycrocker** [comment]
So the issue does seem to be to do with the requirement that the same sites not be selected twice. When all filtering is disabled, the error still occurs, but does not if the requirement of never selecting twice is disabled. Do we still need the requirement? The error seems to occur when the preferred sites are being re-selected often enough that there are no sites left in rankings that are not also in prefseedsites or prefshadesites, which would make the ranking meaningless anyway.  I think either we need to remove the requirement or put in an extra catch for when rankingsin becomes empty.

**Comment by ConnectedSystems** [comment]
Yes, agree we can now remove the requirement that repeated sites be avoided. This was a interim solution to ensure intervened locations were spread around over time - something I'm now not sure is needed/warranted given other changes.

**Comment by Rosejoycrocker** [comment]
Ok cool, I'll do this :)

**Comment by ConnectedSystems** [comment]
Is this issue resolved now?

**Comment by Rosejoycrocker** [comment]
I'll double check, I can't remember whether it was something I  folded into the `make mcda generic` PR or whether it was separate

**Comment by Rosejoycrocker** [comment]
I think this is resolved, I ran the MWE and it ran fine

**Comment by ConnectedSystems** [comment]
Thanks Rose
