### ISSUE TITLE
Register v0.7.0

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#388]
@JuliaRegistrator register

## What's Changed
* Update docstrings for growth function by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/375
* Add map visualization - displays k-area by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/356
* Consider near-term conditions with greater weight than far-future conditions by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/387
* Changes to number of species in ADRIA by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/380
* Temporal clustering for spatial data by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/382

**Full Changelog**: https://github.com/open-AIMS/ADRIA.jl/compare/v0.6.0...v0.7.0

**Comment by ConnectedSystems** [comment]
@JuliaRegistrator register

**Comment by ConnectedSystems** [comment]
@JuliaRegistrator register branch=v0.7.0-release-fix

**Comment by ConnectedSystems** [comment]
@JuliaRegistrator register branch=v0.7.0-release-fix

**Comment by ConnectedSystems** [comment]
Closing as registration PR has been merged
