### ISSUE TITLE
Add Rule Induction (with SIRUS)

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#404]

**Comment by Zapiano** [comment]
After running some model for different scenarios, applying time series clustering and identifying one of them as of interest, we want to use SIRUS package [1] to extract a set of rules that characterize this cluster.

Our desired code flow is something like the following:

```julia
# Run the scenarios ...
rs = ADRIA.run_scenarios(scens, dom, "45")

# Extract metric from scenarios (in this case total absolute cover)
scenario_tac = ADRIA.metrics.scenario_total_cover(rs)

# Cluster scenarios
n_clusters = 6
clusters = ADRIA.analysis.time_series_clustering(scenario_tac, n_clusters)

# Classify clusters using the median of each cluster as metric
# return a vector of 1 (of interest) and 0 for each time series
classified_scenarios = ADRIA.analysis.classify_series_clusters(scenario_tac, clusters, metric=median)

# Choose which features are to be used
features = [] # Vector of features names
filtered_features = rs[:, features] # does that work?

# Extract rules from scenarios using only 
cluster_rules = ADRIA.analysis.cluster_rules(filtered_features, classified_scenarios)
```

# Questions

- Is there anything else we want as an output (regarding this particular issue)? 
- What do we want to do with that in terms of visualization?


# References

[1] https://sirus.jl.huijzer.xyz/dev/binary-classification/

**Comment by ConnectedSystems** [comment]
> ```
> # Choose which features are to be used
> features = [] # Vector of features names
> filtered_features = rs[:, features] # does that work?
> ```

You've already figured it out but `scens` is your scenario spec with the features (essentially your `X`)

You can also extract it from a Result Set if you've loaded the data from a previous run:

```julia
rs = ADRIA.load_results("... path to some results...")
scens = rs.inputs
```

```julia
# Note: This really should be updated so we only need to pass in the Domain rather than a field
ADRIA.component_params(dom.model, [Name_of_components_of_interest, ...])
```

I also wonder how sensible it would be to extract rules for a specific feature one by one?

```julia
#  Extract rules for a each feature at a time
feat_rules = Rules[]  # or whatever the type is
for feat in features
    feat_rules[i] = ADRIA.analysis.cluster_rules(feat, classified_scenarios)
end
```

and then use the rules altogether?

Regarding visualization, plotting all the levers with a box indicating the relevant decision-relevant spaces would be nice... have to think more on that

Robust Scenario Analysis is outside the scope of this issue so I'll stop there.
