### ISSUE TITLE
Errors when running scenarios in parallel when nworkers() > 1

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#413]
https://github.com/open-AIMS/ADRIA.jl/blob/6bdbe38171100ec2cc7b1870467aba1adabf6adf/src/scenario.jl#L126C1-L130C16

When running more than 4095 scenarios the function `run_scenarios` will run in the scenarios in parallel. If nworkers() using more than one worker, `fun` won't be defined, but then at the lines 127 and 129 it will be called, raising the following error at line 127 of this file: `ERROR: UndefVarError: 'func' not defined`

**Comment by ConnectedSystems** [comment]
How are you hitting this error? (i.e., running scenarios in parallel more than once?)

The `nworkers()` check is there so that you don't repeatedly and unnecessarily add more and more workers.
The first time you run in parallel, the functions get defined. The second time, the workers were either removed (see flow for `remove_workers==true`) and the process repeats, or the workers were kept so that part of the logic is unnecessary.

FYI, `remove_workers` is set to true by default as it can use a lot of memory. In most cases I imagined you'd want to free memory so that analysis can be done.

I suspect the first run errored? Meaning workers were not spun up?

**Comment by Zapiano** [comment]
What do you mean by "more than once"? I run scenarios with `num_samples = 4096` and I didn't get any error. Than I run again and I got the error. And since then I get the same error again and again...

Do you think after running the first time I run the workers weren't removed?

**Comment by ConnectedSystems** [comment]
More than once, meaning run scenarios multiple times

```julia
scens = ADRIA.sample(dom, 4096)
ADRIA.run_scenarios(scens, dom)

scens = ADRIA.sample(dom, 8192)
ADRIA.run_scenarios(scens, dom)
```

Can you try:

```julia
ADRIA._remove_workers()
```

and see what happens?

**Comment by Zapiano** [comment]
I run 
```
ADRIA._remove_workers()
```

and run the code, and got the following error:

```
ERROR: On worker 55:
IOError: unlink("C:\\Users\\pribeiro\\.julia\\compiled\\v1.9\\ADRIA\\jl_CE3.tmp"): permission denied (EACCES)
```

and after that every time I run again I get the `func not defined` error.

Then I removed workers again, with the same command, and I got the following different error:

```
ERROR: On worker 56:
UndefVarError: `#141#143` not defined
```
and, again, after that, every time I run it again I get the `func not defined` error. 

🤔

**Comment by ConnectedSystems** [comment]
Just to confirm, is this on both your laptop and remote desktop or just one?

I'm starting to suspect anti-virus is interfering...

**Comment by Zapiano** [comment]
@ConnectedSystems I am running in my laptop now, the ETA is around 40min, but it seems to be working.

**Comment by Zapiano** [comment]
@ConnectedSystems It took me a while to run it here because my REPL crashed (and I had to decrease the number of workers) but yes, it worked on my personal laptop.

So, should I close this issue then?

**Comment by ConnectedSystems** [comment]
Leave it open, I'll raise a ticket with IT to see if it's the anti-virus

**Comment by ConnectedSystems** [comment]
Can confirm it's an issue on the remote desktop, and it is not anti-virus related. Not sure what's happening there.

Need to double check what happens on laptop.

**Comment by ConnectedSystems** [comment]
@Zapiano 

I have a possible fix for parallel runs crashing workers on the remote desktop 😄 

> Running 8192 scenarios for RCP 45 100%|████████████████████████████| Time: 0:06:44

Running a few more times to see if the crash still occurs.

**Comment by Zapiano** [comment]
@ConnectedSystems good! On that: today I managed to run 4096 scenarios in parallel but I had to Elevate first... 🤔

**Comment by ConnectedSystems** [comment]
Nope, seems I'm just delaying the issue - it comes back with larger runs...
