### ISSUE TITLE
Change the way `target_cluster` function is works

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#423]
Instead of having a function inside `rule_extraction.jl` that finds the index of the `target_cluster`, it would be better to have a function inside `time_series_clustering.jl` that returns a version of the clusters vector but only with 1s and 0s (for target and non target clusters). The advantages of this approach are:

- We would be able to easily plot those two clusters and say something like "these 6 clusters that we had before are now this two clusters"
- `target_cluster` is now being called inside both `cluster_rules` (function that uses SIRUS to extractr rules) and `viz.rules_scatter`. With this approach, we can just pass this vector of clusters to both and be more certain that they both are using the same information
- This way is also easier to compute things like the variance of the target cluster in the future to assess how good this `target_cluster` is

**Comment by ConnectedSystems** [comment]
I think I agree.

Later on we would want the user to be able to do the entire process with a single function call I think.

The workflow would be something like:

1. User runs some scenarios
2. With the scenarios, the user would like to identify the most performant cluster according to a (meta-)metric
3. Print or visualize the identified rule sets for the scenarios identified with 2

On top of that, we would want to allow other ways of identifying scenarios of interest (such as the robustness criteria I spoke of earlier today, e.g., a set of metrics maintaining a median score > 30th percentile over time). Would be interesting to see a comparison.
