### ISSUE TITLE
Out of memory error when calculating PAWN sensitivity for 8192 scenarios

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#450]
When calculating the PAWN sensitvity index for 4096 scenarios with the Moore domain, the output in calculated without error. However, for 8192 scenarios, a memory-error out of gc handles error message is produced.

This occurs both on the remote desktop and personal laptop.

MWE for issue:

```julia

here = @__DIR__
dom = ADRIA.load_domain(joinpath(here, "Domain path"), "45")
k = 13
N = 2^k
scens = ADRIA.sample_guided(dom, N)
foi = [:guided]
rs = ADRIA.load_results("Results path")

mean_abs_cc = ADRIA.mean(sum(ADRIA.total_absolute_cover(rs)[:, :, :], dims=:sites), dims=:timesteps)[timesteps=1, sites=1]

infil> ADRIA.sensitivity.pawn(scens[:, string.(foi)], NamedDims.unname(AxisKeys.keyless(mean_abs_cc)))
ERROR: syntax: invalid syntax (memory-error out of gc handles)
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Comment by ConnectedSystems** [comment]
```
mean_abs_cc = ADRIA.mean(sum(ADRIA.total_absolute_cover(rs)[:, :, :], dims=:sites), dims=:timesteps)[timesteps=1, sites=1]
```

This gets the mean `tac` across all scenarios for the first year at site 1, is that correct?
Is there a reason why you're doing this manually yourself? (i.e., do you suspect an issue with the ADRIA methods?)

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker please contact me when you can tomorrow, we need a quick 5min chat

**Comment by Rosejoycrocker** [comment]
> ```
> mean_abs_cc = ADRIA.mean(sum(ADRIA.total_absolute_cover(rs)[:, :, :], dims=:sites), dims=:timesteps)[timesteps=1, sites=1]
> ```
> 
> This gets the mean `tac` across all scenarios for the first year at site 1, is that correct? Is there a reason why you're doing this manually yourself? (i.e., do you suspect an issue with the ADRIA methods?)

Sorry I missed this, no reason. I think I copied parts of an older script but I'll change it to scenario_total_cover
