### ISSUE TITLE
Show labels and units of measurement automatically for plots by default

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#453]
Some plots (like `viz.map` or `viz.ts_cluster`) don't show label names and units of measurement automatically, leaving that to the user.

**Comment by ConnectedSystems** [comment]
Options as I see it:

1. Create a new type, say `Outcome`, which provides an interface to all metric/performance results, including relevant metadata.
    This new type will otherwise behave identically to NamedDimsArray/AxisKey types.

2. Rewrite all metric/performance/analysis methods to accept a function, and use the metadata included in `Metric` types to determine auto-magically what to include/display in the visualizations.

There may be a third option that is inbetween these two extremes but I think the first is our cleanest way forward. 

Unfortunately, the first option also requires rewrite of all visualization functions as well.
