### ISSUE TITLE
Conceptually align all coral cover calculations to be relative to `k` area

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#480]
Currently simulations (and subsequent analyses) are run using two conceptualizations of coral cover.

Calculations are performed with values expected to be relative to either total location area, or the locations' coral carrying capacity ($k$ area) - this 

This results in convoluted (and often duplicate/unnecessary) code that can cause confusion.

TODO:

- [x] #487
- [x] #488
- [x] #483
- [x] #484
- [x] #501

**Comment by ConnectedSystems** [comment]
Changes in the `consistent-cover` branch tentatively resolves #488 .

**Comment by Rosejoycrocker** [comment]
Hey @ConnectedSystems, I checked the MCDA files for related changes and there may need to be some changes to how some of the criteria are calculated, I'm adding this as a TODO for myself.
