### ISSUE TITLE
`_time_labels` gives duplicate labels in some cases 

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#495]
Depending on the labels passed to `_time_labels` it might miss or not the last label, but now we are always adding it - which causes an error because of duplicated labels sometimes.

`tick_pos` gives the tick label positions + 1
`tick_label` finds the corresponding values, but then always adds the last label again

One option is to check to see if the last label is a duplicate before adding.

**Comment by ConnectedSystems** [comment]
Thanks for this.

Had a thought: it would be nice to always include the initial time step as well. 

I'm okay merging this (after a light review) but just wanted to give you the option of adding the initial time step in this PR rather than making another one.
