### ISSUE TITLE
Register v0.9.0

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#498]
@JuliaRegistrator register

Release notes:

## What's Changed
* Miscellaneous changes to improve type infererability and precompilation times by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/455
* Changes to improve performance of PAWN sensitivity analysis by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/457
* Fix print_rules condition by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/460
* Update ADRIA logo by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/461
* Adjust PAWN function to support 1D matrix for convenience by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/462
* Update Reef Tourism Index regression coefficient (temporary solution) by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/466
* Include rule_extraction.jl in viz.jl by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/468
* Add new cluster_rules method that accepts BitVector or Vector{Bool} by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/467
* Add option to show GBRMPA management zones by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/470
* Precompilation reduction by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/469
* Update sensitivity module to follow Blue style by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/471
* Update Doc mentioning blue style guide by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/472
* Update viz.rules_scatter to accept targeted clusters by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/475
* Remove locations with no space from consideration for interventions by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/479
* Rename time_series_clustering and ts_cluster by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/478
* Fix duplicate x-axis values bug in `viz.outcome_map()` by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/442
* Add Documentation Sensitivity section for Rule Induction algorithm by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/477
* Update version number to 0.9.0 by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/497

**Full Changelog**: https://github.com/open-AIMS/ADRIA.jl/compare/v0.8.0...v0.9.0

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker @Zapiano don't forget to close the issue after release is completed 😄
