### ISSUE TITLE
Adjust usage of k site area in location selection to align with coral cover being relative to k

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#501]
Relative coral cover is changing to be relative to k area rather than total site area. This should be reflected in the usage of coral cover area in location selection.

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker can this be closed now due to #547 ?

**Comment by Rosejoycrocker** [comment]
> @Rosejoycrocker can this be closed now due to #547 ?

Yep, I'll close it

**Comment by Rosejoycrocker** [comment]
Issue dealt with in #457

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker  #457 or #547 ?
