### ISSUE TITLE
Remove `top_n` from distance sorting as no longer needed

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#509]
`top_n` is used to define the number of sites to select the sites satistfyng the distance threshold from. In most cases a restriction on this is unnecessary and should be removed as it clouds SA analyses.

**Comment by ConnectedSystems** [comment]
Was this addressed already Rose?

**Comment by Rosejoycrocker** [comment]
Closed in #514

**Comment by Rosejoycrocker** [comment]
> Was this addressed already Rose?

Yes sorry, I thought I had linked the issue in the PR but I hadn't.
