### ISSUE TITLE
[RFC] Change factors marked as "integer" types to "discrete"

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#512]
Recent changes distinguish "categorical" factors (e.g., `guided`) from other "integer"-based factors (e.g., `N_seed_TA`).

We should consider signposting what these other "integer" factors are explicitly by changing these to "discrete" or other suitable marker.

What implications are there if we do this @Zapiano @Rosejoycrocker ?

**Comment by Rosejoycrocker** [comment]
As discussed with @Zapiano, it would be more consistent with the change from "integer" to "discrete" to change parameters designated as "real" to "continuous". 

I believe there was talk around using "unordered categorical" for integers and "ordered categorical" for categorical variables. To me categorical implies a mapping, such as unguided mapping to 0, counterfactual mapping to -1, so I'm not sure about "unordered categorical" being used for integers. For example for `N_seed_TA` the integers directly represent a quantity of corals so there is no mapping I can see. That's just my interpretation of categorical though, having mostly used it in mathematics/statistics contexts.

**Comment by ConnectedSystems** [comment]
Hi @Rosejoycrocker 

I agree that "categorical" is not appropriate for a unit quantity like number of corals. Is there a more specific term for such values?

"discrete" was my attempt at a catchall.

Agree also with changing "real" to "continuous".
