### ISSUE TITLE
[Bug] Plotting subset of scenarios fail as not all scenario types may be included

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#522]
Scenario plots break when targeting specific scenario conditions.

The usual approach seems to be broken now:

https://github.com/open-AIMS/ADRIA.jl/blob/2cc3f6f91becdcb9f815b011dd9921879c4c4a7d/ext/AvizExt/viz/scenarios.jl#L236

MWE:

```julia
rs = ADRIA.load_results("...")

target_scens = (rs.inputs.guided .== 0) .& (rs.inputs.SRM .< 1.0)

# Subset using Scenario IDs
s_tac = ADRIA.metrics.scenario_total_cover(rs; scenarios=findall(target_scens))

ADRIA.viz.scenarios(rs, s_tac)
# ERROR: BoundsError: attempt to access 75×271 Matrix{Float64} at index [1:75, 4096-element BitVector]
```

But even if the error above is fixed, you'll run into an issue with this line:
https://github.com/open-AIMS/ADRIA.jl/blob/2cc3f6f91becdcb9f815b011dd9921879c4c4a7d/ext/AvizExt/viz/scenarios.jl#L96C1-L96C1

It expects all scenario types to be present in a given set of scenario outcomes.

MWE:

```julia
dom = ADRIA.load_domain("...")
scens = ADRIA.sample(dom, 4096)
# rs = ADRIA.run_scenarios(dom, scens, "45")
rs = ADRIA.load_results("...")

# Let's look at unguided scenarios with low SRM
target_scens = (rs.inputs.guided .== 0) .& (rs.inputs.SRM .< 1.0)

# Hacky workaround until we support plotting subsets of scenarios again
# Copy original scens as a back up
orig_scens = copy(rs.inputs)

# Filter dataframe down to target
rs.inputs .= filter!(row -> (row.SRM < 1.0) & (row.guided == 0), rs.inputs)

# Get subset of scenario outcomes
s_tac = ADRIA.metrics.scenario_total_cover(rs; scenarios=findall(target_scens))

ADRIA.viz.scenarios(rs, s_tac)
# ERROR: BoundsError: attempt to access 0-element Vector{Tuple{Symbol, Float64}} at index [1]
```

**Comment by Zapiano** [comment]
@ConnectedSystems 

Why not passing the filter to the plotting function?

```
rs = ADRIA.load_results("...")

s_tac = ADRIA.metrics.scenario_total_cover(rs)

target_scens = (rs.inputs.guided .== 0) .& (rs.inputs.SRM .< 1.0)

ADRIA.viz.scenarios(rs, s_tac; filter=target_scens)
```

I like the idea of filtering when computing the metric, but the problem is that when you do that you have `rs.input` and `s_tac` with different numbers of scenarios, so it's hard to keep track of which one is guided, unguided, etc. Also if we want to apply multiple filters it might be hard. 

What do you think?

**Comment by ConnectedSystems** [comment]
Good idea, and one the metrics use already so makes sense to standardise. 

That said, if the outcomes themselves are filtered, then it won't work so well.

The scenario IDs still be part of the named array so I suggest we use that for now. But this entire problem will be simplified when we adopt data structures that handle metadata as well (e.g., YAXArrays)

**Comment by Zapiano** [comment]
> Good idea, and one the metrics use already so makes sense to standardise.

I don't understand that. Which metric?

**Comment by ConnectedSystems** [comment]
> > Good idea, and one the metrics use already so makes sense to standardise.
> 
> I don't understand that. Which metric?

All metrics. At least all scenario metrics.

**Comment by Zapiano** [comment]
> The scenario IDs still be part of the named array 

Of course! I've forgotten about that! Thanks ;)
