### ISSUE TITLE
Make SRM apply to Reef clusters not whole of GBR

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#525]
Currently fogging site selection is applied on a sitewise basis. Moving forward, there should be the option to select locations for SRM so that when doing SRM on a GBR scale it is not applied to the whole GBR. The MCDA should be adapted to allow for selection of a set of reefs to apply SRM at for when modelling at the GBR scale, as well as maintaining the option to fog on a site by site basis.

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker I don't follow this - as I explained, SRM is currently applied to the entire spatial domain not a "sitewise" basis.

It does mean that when running GBR-scale scenarios, the entire Reef is shaded.

**Comment by Rosejoycrocker** [comment]
Sorry this is worded incorrectly. It should say shading is currently applied on a site by site basis but we want the option for MCDA to be on a Reef by Reef basis so when we are doing SRM its not over the whole GBR

**Comment by ConnectedSystems** [comment]
> It should say shading is currently applied on a site by site basis

But it's not? 

Just to clarify: 
- Shading via fogging is applied on a site-by-site/reef-by-reef basis.
- Shading by SRM (cloud seeding/brightening) is not.

**Comment by Rosejoycrocker** [comment]
Yes so shading in the mcda (fogging) is currently applied on a site by site basis. If we want to do SRM at the GBR scale without shading the whole GBR we need to be able to do site selection on a Reef-by-Reef basis rather than just shading everywhere. So, for example, the decision matrix would have an aggregated form with reefs along the rows rather than sites.

**Comment by ConnectedSystems** [comment]
Okay, I guess what caused the confusion here is the use of the word "but" in this sentence:

_"shading is currently applied on a site by site basis **but** we want the option for MCDA to be on a Reef by Reef basis"_

**Comment by Rosejoycrocker** [comment]
Sorry I updated the first description in the PR but not my other comment. How does it sound now?

**Comment by ConnectedSystems** [comment]
Could you replace "shade" with "fog"/"fogging" or "SRM" as appropriate to avoid confusion please?

**Comment by Rosejoycrocker** [comment]
This issue is no longer relevant as SRM will be provided as an enviromental layer
