### ISSUE TITLE
Develop cyclone mortality models based on R implementation

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#529]
Following the approach on

https://aslopubs.onlinelibrary.wiley.com/doi/epdf/10.4319/lo.2008.53.2.0690

Part of #516 

There are 5 Cyclone categories base on windspeed (according to [BOM site](http://www.bom.gov.au/cyclone/tropical-cyclone-knowledge-centre/understanding/categories/) and that the above paper is using):

- category 1: 17 – 24.5 m/s
- category 2: 24.6 – 32.5 m/s
- category 3: 32.6 – 44.2 m/s
- category 4: 44.2 – 55.3 m/s
- category 5: > 55.3 m/s

Following there's a description of the approach I'm going to take to address this issue:

- Write a script inside the [RRAP Data Generators repo](https://github.com/open-AIMS/rrap-dg) that generates a NetCDF4 file with coral mortality data 
  - This will be a 3-Dimensional "datacube" with dimensions:
    - timesteps
    - location
    - coral group (by type/species and depth)
    - cyclone scenario/trajectory
  - Initially, each scenario is a sequence of windspeed values for each timestep. Then, for each coral_group, we translate that into mortality rates (which are based solely on windspeed)
  - Mortality data will come from the regression model from the R script we received from C~Scape team
  - Windspeed scenarios will come from ReefMod data package

This is going to be partly addressed by this `rrap-dg` repository PR: https://github.com/open-AIMS/rrap-dg/pull/1

But it will also be necessary to change ADRIA external interface to read this data from the Data Package.

**Comment by Zapiano** [comment]
@ConnectedSystems Can you refresh my mind about our discussing earlier? 

1. I have the impression that we talked about a 4 dimensional datacube but thinking about it now it seems that we only need a matrix (as I described above)
2. What should I do after running that script and having this .nc file?

**Comment by ConnectedSystems** [comment]
The 4D cube was mortality across:

- timesteps
- location
- species group
- cyclone scenario/trajectory

I imagine 4 dimensions are necessary because the mortality for each species group would be different

**Comment by Zapiano** [comment]
1. The mortality doesn't depend on the location, so, why this dimension?
2. How am I supposed to simulated scenarios? And how many? I thought I would just provide the information of mortality per windspeed and let ADRIA simulate the scenarios.

**Comment by ConnectedSystems** [comment]
1. Mortality doesn't - but cyclones don't happen at all locations at the same time...
2. I thought the idea was to have a datacube of mortalities

For example, a cyclone scenario for 1 location, 1 species:

Mortality / timestep: [0.0, 0.0, 0.0, 0.233, 0.133, 0.0, 0.0, ... 0.125, 0.1, 0.0]

**Comment by Zapiano** [comment]
I have updated the description of this issue then. I didn't include the "location" dimension (yet) because the mortality doesn't depend on that. Do you know if the scenarios (sequence of windspeed values) depend on the locations?

**Comment by Zapiano** [comment]
> I have updated the description of this issue then. I didn't include the "location" dimension (yet) because the mortality doesn't depend on that. Do you know if the scenarios (sequence of windspeed values) depend on the locations?

This is actually wrong. The cyclone scenarios depend on the location, that's why this dimension is needed.
