### ISSUE TITLE
Out of memory error for parallelised runs for whole of GBR domain

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#535]
When running 8192 runs for the whole of GBR Domain with 20 cores a ECCONRESET error is triggered at https://github.com/open-AIMS/ADRIA.jl/blob/533d47885607d0f810561322b271429146d16613/src/scenario.jl#L163

Trying the same runs with fewer cores and an increased connection time (300s) results in an OutofMemory error at the same position (L163).

**Comment by ConnectedSystems** [comment]
Just loading up data with a single core can take up to ~6GB of ram when working with whole of GBR datasets.

Doing some back of the envelope calculations, the workstation we have has 128GB of ram but some of that will be taken up by the operating system and background processes. With 20 workers using ~6GB each, 128GB itself is cutting it close: 128 / 6 $\approx$ 21.33, so doesn't leave much headroom to begin with not even considering the fact we don't have the full 128GB.

On top of that I've found several places where memory use could be more efficient.

Will look into what can be done here.

**Comment by Rosejoycrocker** [comment]
Thanks @ConnectedSystems . So should it be possible to run as is on the HPC or should this be resolved before I try there?
