### ISSUE TITLE
Add `load_latest_results()`

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#548]
It would be handy to load the latest result set found in a given a directory/path:

```julia
rs = ADRIA.load_latest_results("some path")
```

**Comment by Zapiano** [comment]
@ConnectedSystems what would be the difference between this and `ADRIA.load_results()`? What would this function do/return?

**Comment by ConnectedSystems** [comment]
In discussion it was determined that a function that displays a list of result sets in a given folder that matches some user provided criteria (time/date range run, number of scenarios, etc) is more useful.

Closing in favour of the above.
