### ISSUE TITLE
Compute mean of truncated distribution using a Burman series

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#572]
Now we are creating a `truncated(Normal(...))` distribution and then calling the `mean` function to find the mean (see`src/ecosystem/corals/growth.jl:311`). We can do this in a different way. Suppose we have a distribution `f(x)` and we want to find the mean within the interval `[a,b]`, then we could do integrate `x*f(x)` within the interval `[a,b]`. But also: instead of actually integrating, we could use the [Burman series of the error function](https://en.wikipedia.org/wiki/Error_function#B%C3%BCrmann_series) to approximate the value of this integral. This way we would save memory and time (I hope).

**Comment by Zapiano** [comment]
@ConnectedSystems @Rosejoycrocker  Can you check if I missed something and if it makes sense?

**Comment by Rosejoycrocker** [comment]
Just adding the link here for reference:

https://github.com/open-AIMS/ADRIA.jl/blob/a85588322bb4c6503092d91280907fe1c2b86ba5/src/ecosystem/corals/growth.jl#L310-L312

**Comment by Rosejoycrocker** [comment]
> @ConnectedSystems @Rosejoycrocker Can you check if I missed something and if it makes sense?

Makes sense to me, is the intent not just to add the approximation but understand the order of truncation best suited for the application? For example by comparing the first, second and third order approximations, (k=1,2,3) and comparing their mean squared error to the Julia function equivalent.

**Comment by Zapiano** [comment]
@ConnectedSystems @DanTanAtAims does it make sense to keep this issue opened?

**Comment by ConnectedSystems** [comment]
Yes, the last set of work hasn't been merged yet.
