### ISSUE TITLE
Remove unused version check 

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#580]
This line checks if the datapackage version is bigger than "0.2.1" https://github.com/open-AIMS/ADRIA.jl/blob/916e947b9a7f22f1d69cd7137a1de2ba18bb530a/src/ExtInterface/ADRIA/Domain.jl#L274

BUT it's impossible to load a datapackage with that version, because it is not listed here: https://github.com/open-AIMS/ADRIA.jl/blob/916e947b9a7f22f1d69cd7137a1de2ba18bb530a/src/ADRIA.jl#L102

So we should just remove the check.

**Comment by Zapiano** [comment]
@ConnectedSystems FYI

**Comment by ConnectedSystems** [comment]
The first link points to a line that checks if the start year is earlier than the end year?

**Comment by Zapiano** [comment]
This is the line I meant:
![image](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/ad70b1f5-d149-4bf3-9a88-2620eb4c1828)

**Comment by Zapiano** [comment]
@ConnectedSystems updated the description to match the right line - that in my branch must be different.

**Comment by ConnectedSystems** [comment]
Bigger or equal to.

The check there is when a very old datapackage was being loaded.

I suggest putting in a deprecation warning and mark for removal later.

**Comment by Zapiano** [comment]
> Bigger or equal to.
> 
> The check there is when a very old datapackage was being loaded.
> 
> I suggest putting in a deprecation warning and mark for removal later.

But any datapackage with version smaller than that will never get to this line because it wont pass this one: https://github.com/open-AIMS/ADRIA.jl/blob/916e947b9a7f22f1d69cd7137a1de2ba18bb530a/src/ExtInterface/ADRIA/Domain.jl#L269C36-L269C36

**Comment by ConnectedSystems** [comment]
Yes I see - then I agree, it should be removed.
