### ISSUE TITLE
Move example scripts into the cookbook

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#584]
We now use a cookbook approach as our "how-to" guides.

https://open-aims.github.io/ADRIA.jl/stable/usage/cookbook/

We have a legacy set of example scripts for the same purpose. Some have already been moved into the cookbook, but others are now outdated and no longer necessary.

- [ ] Compare examples in the `examples` directory and in the cookbook
- [ ] Copy missing examples into the cookbook, updating as necessary. Ask the team for help as needed.
- [ ] Delete the `examples` directory

**Comment by Zapiano** [comment]
@ConnectedSystems One important point here is that there is an `Example_domain` dir inside `examples`, and that is used for testing. Should we move this (`Example_domain`) to the `test` dir?

**Comment by ConnectedSystems** [comment]
Yes

**Comment by ConnectedSystems** [comment]
Closed by #651
