### ISSUE TITLE
Changes in PR#552 breaks scenario visualizations

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#587]
The changes to "Split `confinit_scenarios`" (which is actually referring to `scenarios_confint()`) in (https://github.com/open-AIMS/ADRIA.jl/pull/552) break scenario visualizations.

There are in fact a number of issues.

Example:

```julia
using Revise, Infiltrator
using WGLMakie, GeoMakie, GraphMakie
using ADRIA


dom = ADRIA.load_domain("path to Domain")
scens = ADRIA.sample(dom, 8)
rs = ADRIA.run_scenarios(dom, scens, "45")

stac = ADRIA.metrics.scenario_total_cover(rs)
ADRIA.viz.scenarios(rs, stac)
```

The last line raises:

```julia
ERROR: MethodError: Cannot `convert` an object of type Base.KeySet{Symbol, Dict{Symbol, BitVector}} to an object of type Vector{Symbol}

Closest candidates are:
  convert(::Type{<:Array}, ::LabelledArrays.LArray)
   @ LabelledArrays C:\Users\tiwanaga\.julia\packages\LabelledArrays\FI31L\src\larray.jl:145
  convert(::Type{Array{T, N}}, ::AxisArrays.AxisArray{T, N}) where {T, N}
   @ AxisArrays C:\Users\tiwanaga\.julia\packages\AxisArrays\CtyI0\src\core.jl:311
  convert(::Type{<:Array{<:Any, N}}, ::Symbolics.Arr{<:Any, N}) where N
   @ Symbolics C:\Users\tiwanaga\.julia\packages\Symbolics\gBKZv\src\arrays.jl:746
  ...

Stacktrace:
  [1] _confints(outcomes::NamedDims.NamedDimsArray{(:timesteps, :scenarios), Float64, 2, AxisKeys.KeyedArray{Float64, 2, Matrix{Float64}, Tuple{Vector{Any}, UnitRange{Int64}}}}, scen_groups::Dict{Symbol, BitVector})
    @ AvizExt c:\Users\tiwanaga\projects\ADRIA.jl\ext\AvizExt\viz\scenarios.jl:136
```

Stacktrace points to this:
https://github.com/open-AIMS/ADRIA.jl/blob/4a8fc158b664ea65e0d1e510453ee02ea1aefc45/ext/AvizExt/viz/scenarios.jl#L136

Where:

`groups::Vector{Symbol} = keys(scen_groups)`

Should be:

`groups::Vector{Symbol} = collect(keys(scen_groups))`

Here: https://github.com/open-AIMS/ADRIA.jl/blob/4a8fc158b664ea65e0d1e510453ee02ea1aefc45/ext/AvizExt/viz/scenarios.jl#L143

`ordered_groups` is not defined anywhere.

Assuming `groups` is the intended variable, it then leads to an issue here:
https://github.com/open-AIMS/ADRIA.jl/blob/4a8fc158b664ea65e0d1e510453ee02ea1aefc45/ext/AvizExt/viz/scenarios.jl#L249

The method seems to be overly constrained to `NamedDimsArray`, where in actual use base Arrays can be passed in.

Once that is corrected for, it then leads to:
https://github.com/open-AIMS/ADRIA.jl/blob/4a8fc158b664ea65e0d1e510453ee02ea1aefc45/ext/AvizExt/viz/scenarios.jl#L256

Raises: `ERROR: BoundsError: attempt to access 75×2×3 Array{Float64, 3} at index [1:75, 8-element BitVector]`

The method seems to be expecting a matrix of scenario outcomes but the PAWN analysis results are being passed in?

I stopped investigating at this point.

**Comment by Rosejoycrocker** [comment]
I'll look into it
