### ISSUE TITLE
Use min-max normalisation for heat stress criteria

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#592]
Currently the heat stress criteria is normalised (prior to matrix normalisation) by division by 20DHW (deemed an upperlimit in terms of irrevokable damage to corals). For smaller DHWs, however, this way of normalising gives little variation between sites, such as below:
![decision_matrix_map_moore](https://github.com/open-AIMS/ADRIA.jl/assets/56939532/379ac449-b638-4820-bc94-f0db4fb280c7)

Min-max normalisation allows better differentiation between sites which will allow the site selection algorithm to better differentiate between suitable sites for deployment, as shown below:
![decision_matrix_plots_heat_stress_minmax_moore](https://github.com/open-AIMS/ADRIA.jl/assets/56939532/1b2041b9-81c1-4d6a-a525-33dd8b180fcb)

**Comment by Zapiano** [comment]
@Rosejoycrocker why do you reckon only heat_strees was hugely affected by this change? Any hypotesis?
