### ISSUE TITLE
Update use of Makie (v0.20.0) to avoid deprecations

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#600]
Makie v0.20.0 was released recently (see [here](https://blog.makie.org/blogposts/v0.20/))

This comes with a number of performance improvements and support for HiDPI screens, as well as a few deprecations.

I think we should be mostly okay, but one notable change is that `resolution` is now `size`:

```
# Instead of this:
tf = Figure(resolution=(1600, 600))

# Do this:
tf = Figure(size=(1600, 600))
```

FYI @Zapiano this means more seamless plotting between CairoMakie and other backends, especially on Mac (because of the improved HiDPI screen support).

WGLMakie gets some performance improvements too.

**Comment by ConnectedSystems** [comment]
> Should we add Makie = 0.20.0 to the [compat] section of Project.toml?

Yes

> Apparently one of the packages we depend on (DimensionalData) depends on version Makie's version 0.19.0. Is that an impediment, since Makie is only used by an extension..?

Also yes. It means we can't update until this package also makes changes to update.

**Comment by Zapiano** [comment]
We are already using more recent versions of Makie.
