### ISSUE TITLE
Loading RME datasets are broken due to cyclone data requirement

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#609]
The error is caused by a missing argument to the `EnvLayer` type due to the recent addition of cyclone data.
The fix is to simply pass in a zero matrix.

Note that RME cyclone data is treated as "waves" as an early workaround, but that should be removed as well.
For RME cyclone data to be used, it would involve translating the cyclone category values into mortality values.
I think that is outside the scope for now...

FYI @Zapiano

**Comment by Zapiano** [comment]
@ConnectedSystems  are you sure `EnvLayer` is the problem? Because I haven't added any attributes to this struct, only to `EnvironmentalLayer`. And I remember we talked about NOT adding cyclone info to `EnvLayer`, so I'm confused about what's going on here and what should be done to fix...
