### ISSUE TITLE
Fix bug in `constrain_reef_cluster` which assumes there will always be enough locations to satisfy the reef constraint

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#656]
Currently `constrain_reef_cluster` assumes there will always be enough locations to satisfy the reef constraint, causing it to error when very stringent values (0-0.4) of `deployed_coral_risk_tol` are used, causing almost all sites to be filtered out prior to applying the reef and area constraints. This causes indexation of an empty variable `add_locs_ind`:

https://github.com/open-AIMS/ADRIA.jl/blob/66380292c8522045c08aae6f74c6a391b2cf8cc9/src/decision/dMCDA.jl#L806

This should be fixed by adding a check for  `add_locs_ind` being empty and breaking out of the loop if this is the case.

**Comment by Rosejoycrocker** [comment]
It was tested, changes to sampling range of `deployed_coral_risk_tol` happened after `constrain_reef_cluster` was added

**Comment by ConnectedSystems** [comment]
My point is that you should be testing each component separately. You don't need to rely on `deployed_coral_risk_tol` to see what happens at extreme cases.

For example, does `constrain_reef_cluster` behave as expected if there are 0 viable locations to 10,000 locations.

If you're running the entire ADRIA suite for your tests, then I can see how testing/development can be very slow.

**Comment by Rosejoycrocker** [comment]
If I'm expecting  `deployed_coral_risk_tol` to be between 0.6-1.0 though, there would never be 0 viable locations due to the nature of the min-max normalisation. I thought "extreme" cases were the extremes of the sampling range.

I was running the mcda specific tests

**Comment by ConnectedSystems** [comment]
> there would never be 0 viable locations due to the nature of the min-max normalisation. I thought "extreme" cases were the extremes of the sampling range.

And now we're in a situation where the sampling range changed and we hit that bug.

> I was running the mcda specific tests

So we need to update those tests to cover these.

But like I said, leave it with me.

**Comment by Rosejoycrocker** [comment]
Yes, I believe this change happened during those changes to parameter definitions in #639 . I thought it was something you decided to do for screnario exploration, but maybe it just happened during a rebase (I only noticed it after my review, sorry) . I think this tolerance should remain between `(0.6,1.0)` , particularly after what the threshold sensitivity analysis showed.

I removed the coral minimum area tolerance when `constrain_reef_cluster` was added, but not `deloyed_coral_risk_tol`.
