### ISSUE TITLE
Larval spread via connectivity is not working as expected

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#686]
Larval spread is currently represented with a matrix multiplication [here](https://github.com/open-AIMS/ADRIA.jl/blob/e9ba1ead6dc94938368d6f1cf36e103a58e2f5a9/src/ecosystem/corals/growth.jl#L705).

I am sceptical that this is appropriate, and this can be shown with a simple test.

Imagine a situation where we are representing fecundity of three functional types across five locations: $\theta\^{(3 \cdot 5)}$.

```math
\theta = \begin{bmatrix} 
  0 \ 32 \ 31 \ 19 \ 61 \\
 27 \ 52 \ 23 \ 43 \ 20 \\
  1 \ 14 \ 62 \ 44 \  7
\end{bmatrix}
```

Each column represents a source location, and each row is the number of larvae produced at that source for each functional type.
**Note that the first element is 0**

We have a connectivity matrix for the five locations: $G\^{(5 \cdot 5)}$

```math
G = \begin{bmatrix} 
0.315604 \ 0.127858 \ 0.0425765  0.279807 \ 0.234154 \\
0.110561 \ 0.540811 \ 0.199668 \ 0.0873666  0.0615929 \\
0.106653 \ 0.27818 \  0.227531 \ 0.253005 \ 0.134631 \\
0.264062 \ 0.305937 \ 9.6802e-5 \ 0.102006 \ 0.327898 \\
0.0338055 \ 0.0689518  0.386821 \ 0.398795 \ 0.111627
\end{bmatrix}
```

---
**A small aside**

The above were generated with:

```julia
θ = floor.(rand(3, 5) .* rand(10:100, 3, 5))
G = rand(5,5)
G = G ./ sum(G, dims=2)
```

The exact example values can be copied with:

```julia
θ = [
  0  32  31  19  61
 27  52  23  43  20
  1  14  62  44   7
]

G = [
 0.315604   0.127858   0.0425765  0.279807   0.234154
 0.110561   0.540811   0.199668   0.0873666  0.0615929
 0.106653   0.27818    0.227531   0.253005   0.134631
 0.264062   0.305937   9.6802e-5  0.102006   0.327898
 0.0338055  0.0689518  0.386821   0.398795   0.111627
]
```

---

Rows of $G$ are sources, columns are sinks. Note in this case the sum of each row of $G$ equals 1.0 but in actuality, it can be < 1.0 (the "missing" portion are larvae that never make it to any destination, assumed to be washed out to sea).

As stated above, the number of larvae that arrive at a sink location is determined with a matrix multiplication:

```math
\theta^\prime = \theta * G
```
Location 1 produces 0 $ft_{1}$ (see $\theta^{(1,1)}$ ), so it should be 0 for all sink locations.

Based on the matrices above, the fecundity for coral type 1 and location 1 is 0 (see $\theta^{(1,1)}$); it never produces any coral larvae for that functional type. Therefore, all sink locations should never receive any $ft_{1}$ from source location 1.

But this is not the result with the matrix multiplication:

```julia
julia> θ * G
3×5 Matrix{Float64}:
 13.9235  35.9484  37.0408  36.9035  19.1838
 28.7543  52.5068  24.5061  30.2791  28.9537
 20.3313  38.8903  19.6568  24.4691  24.6525
```

In contrast, this is what I would expect for sink location 1:

```julia
julia> sum(θ[:, 1]' .* G[:, 1], dims=1)
1×3 Matrix{Float64}:
 0.0  22.4285  0.830686
```

This can be confirmed for $ft_2$ and $ft_3$ with:

```julia
julia> sum(27 .* G[:, 1])
22.428518797096928

julia> sum(1 .* G[:, 1])
0.8306858813739603
```

** note: an additional step to determine the recruitment rate is done so we do not take the floor of values.

**Comment by Rosejoycrocker** [comment]
My understanding of this was that row 1, column 1 $\theta '[1,1]$ is the larvae that flows to site 1 of coral type 1 after one time step. So even though site 1 begins with no larvae it recieves larvae from other sites. Maybe I'm misunderstanding your notation. Is $ft_1$ the first row of $\theta '$?

**Comment by ConnectedSystems** [comment]
> Is $ft_1$ the first row of $\theta^\prime$?

Yes.

> My understanding of this was that row 1, column 1 $\theta\^{\prime}[1,1]$ is the larvae that flows to site 1 of coral type 1 after one time step.

Not after one time step, _at_ a given time step. 

But yes it is - at time $t$, 0 larvae of $ft_1$ are produced at location 1, therefore 0 larvae of $ft_1$ should arrive from location 1.

**Comment by Rosejoycrocker** [comment]
> > Is ft1 the first row of θ′?
> 
> Yes.
> 
> > My understanding of this was that row 1, column 1 θ′[1,1] is the larvae that flows to site 1 of coral type 1 after one time step.
> 
> Not after one time step, _at_ a given time step.
> 
> But yes it is - at time t, 0 larvae of ft1 are produced at source location 1, therefore 0 larvae of ft1 should arrive from source location 1.

I meant as in a single timestep. 

This is how I understand the matrix multiplication,
```math
\theta = \begin{bmatrix} 
  0 \ 32 \ 31 \ 19 \ 61 \\
 27 \ 52 \ 23 \ 43 \ 20 \\
  1 \ 14 \ 62 \ 44 \  7
\end{bmatrix}
\times
G = \begin{bmatrix} 
p_{1,1}\ ...  \ p_{1,5} \\
p_{2,1} \ ...\ \hdots\\
p_{3,1}\ ...\ \hdots \\
p_{4,1} \ ... \ \hdots \\
p_{5,1} \... \p_{5,5}
\end{bmatrix}
= \theta'
\implies \theta'[1,1] = 0 \times p_{1,1} + 32 \times p_{2,1} + 31 \times p_{3,1} + 19 \times p_{4,1} + 61 \times p_{5,1}
```
$\theta`[1,1] =$ (prob. of transition from site 1 to site 1) * (larvae at site 1) + (prob. of transition from site 2 to site 1) * (larvae at site 2) +...+ (prob. of transition from site 5 to site 1) * (larvae at site 5) = total no. of larvae at site 1 after a single time step

**Comment by ConnectedSystems** [comment]
Can you write out what you expect $\theta^\prime$ to be?

**Comment by Rosejoycrocker** [comment]
> Can you write out what you expect θ′ to be?

Like all of $\theta'$ ?

**Comment by ConnectedSystems** [comment]
For location 1

**Comment by Rosejoycrocker** [comment]
I've written it for the first coral type above

**Comment by ConnectedSystems** [comment]
Theta prime Rose, the result of the matrix multiplication.

Based on your understanding with the example values above, what should the result look like for sink location 1

**Comment by ConnectedSystems** [comment]
To be clear, I understand what you're saying, I just want to make sure our understanding of the process and what is being represented is the same

**Comment by Rosejoycrocker** [comment]
This is the process I would expect:
$ θ'[1,1] =$
```julia
infil> θ[1,:].*G[:,1]
5-element Vector{Float64}:
 0.0
 3.537952
 3.306243
 5.017178
 2.0621355

infil> sum(θ[1,:].*G[:,1])
13.9235085
```

**Comment by ConnectedSystems** [comment]
Thank you - okay, so it was an error in how I constructed the example - it should be:

```
θ = [
  0  0  0  0  0
 27  52  23  43  20
  1  14  62  44   7
]
```

to ensure location 1 (or any sink location) receives 0 larvae of $ft_1$

With that out of the way, does it make sense to pass in non-integer values to `recruitment_rate()`?

https://github.com/open-AIMS/ADRIA.jl/blob/e9ba1ead6dc94938368d6f1cf36e103a58e2f5a9/src/ecosystem/corals/growth.jl#L712

**Comment by Rosejoycrocker** [comment]
> Thank you - okay, so it was an error in how I constructed the example, it should in fact be:
> 
> ```
> θ = [
>   0  0  0  0  0
>  27  52  23  43  20
>   1  14  62  44   7
> ]
> ```
> 
> to ensure location 1 (or any sink location) receives 0 larvae of ft1
> 
> With that out of the way, does it make sense to pass in non-integer values to `recruitment_rate()`?
> 
> https://github.com/open-AIMS/ADRIA.jl/blob/e9ba1ead6dc94938368d6f1cf36e103a58e2f5a9/src/ecosystem/corals/growth.jl#L712
> 
> Probably won't make a big difference, but it feels strange to be saying "0.81" of a coral larvae successfully arrived.

I believe so, then there is no larvae to flow to site ones from any other site. Alternatively, if
```math
\theta \times G  = \begin{bmatrix} 
  0 \ 32 \ 31 \ 19 \ 61 \\
 27 \ 52 \ 23 \ 43 \ 20 \\
  1 \ 14 \ 62 \ 44 \  7
\end{bmatrix}
\times
 \begin{bmatrix} 
0\ ...  \ 0.3 \\
0 \ ...\ \0.2\\
0 \ ...\ \0.9 \\
0\ ... \ \0.1 \\
0 \ ... \0.2
\end{bmatrix}

```
Then location 1 would receive no coral type 1 larvae because none is generated on it and there's zero probability of larvae flowing to it from other sites even if they have generated larvae.

Yeah I agree it feels strange. For a Poisson distribution though the rate parameter is the average "no. of events" (in this case no. of larvae) so it's probably ok that it's not a whole number.

**Comment by ConnectedSystems** [comment]
Okay, great to have this discussion documented. I'm going to close as it seems everything is working as expected then.

Next step is to assess the new connectivity data.
