### ISSUE TITLE
Method Call error during testing from rsa function type.

### ISSUE THREAD

**Issue by DanTanAtAims** [open-AIMS/ADRIA.jl#692]
@ConnectedSystems @Rosejoycrocker 

Running tests on main will result in an error during regional sensitivity analysis testing. I believe the change resulted from the merging of #679.

```bash
ERROR: LoadError: MethodError: no method matching rsa(::DataFrame, ::Vector{Float64}, ::DataFrame; S::Int64)
```
with the following partial trace

```bash
   @ ADRIA.sensitivity C:\Users\dtan\repos\ADRIA.jl\src\analysis\sensitivity.jl:545
 [2] test_rs_w_fig()
   @ Main C:\Users\dtan\repos\ADRIA.jl\test\runtests.jl:315
```
My guess is it results from this [line](https://github.com/open-AIMS/ADRIA.jl/pull/679/files#diff-339279e08e2eb261b8ae01ec6343917eccd655e3012a109acfcff7bd9fed62caR456) with the additional parameter.

**Comment by Rosejoycrocker** [comment]
That would be it, I'll fix it ASAP

**Comment by ConnectedSystems** [comment]
@Rosejoycrocker I missed this in my review - what was the reason behind adding the `factors` argument?
There's already an interface method that handles that case:

https://github.com/open-AIMS/ADRIA.jl/blob/5c165ff67bcb86c14103185104927090998fed8a/src/analysis/sensitivity.jl#L547

**Comment by Rosejoycrocker** [comment]
> @Rosejoycrocker I missed this in my review - what was the reason behind adding the `factors` argument? There's already an interface method that handles that case:
> 
> https://github.com/open-AIMS/ADRIA.jl/blob/5c165ff67bcb86c14103185104927090998fed8a/src/analysis/sensitivity.jl#L547

I think I missed this. I can remove the `factors ` method from the main method but might be good to add it as input to the test anyway because it takes a while to run through all the factors

**Comment by ConnectedSystems** [comment]
It doesn't run through all the factors - you can see the interface subsets down to the factors you ask for.

Unless you're saying the tests apply it to all factors?

That said, I've never noticed a runtime issue with RSA tests, it's usually testing full runs with SIRUS that takes up the majority of the time.

**Comment by Rosejoycrocker** [comment]
ah ok, must have been something else slowing rsa down. Anyway, I'll remove the requiremnet in the new rsa
