### ISSUE TITLE
`viz.outcome_map` not working when `:guided` is one of the factors of interest

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#713]
After running scenarios, if I try to plot an `outcome_map` running:

```
s_tac = ADRIA.metrics.scenario_total_cover(rs)
mean_s_tac = vec(mean(s_tac, dims=1))
foi = [:dhw_scenario, :wave_scenario, :guided]
tac_om_50 = ADRIA.sensitivity.outcome_map(rs, mean_s_tac, x -> any(x .>= 0.5), foi; S=20)
ADRIA.viz.outcome_map(rs, tac_om_50, foi)
```

I get the following error:

![image](https://github.com/open-AIMS/ADRIA.jl/assets/8040719/d23084eb-d2c3-45a1-9ea5-e9aa60f20ac8)

The same doesn't happen if I remove `:guided` from `foi`. 

Inside `ADRIA.jl\ext\AvizExt\viz\sensitivity.jl` method `outcome_map!`, there's the following bit of code

```
if f_name == :guided
    fv_s = collect(1:length(fv_labels))
else
    fv_s = round.(quantile(f_vals, b_slices), digits=2)
end
``` 

That seems to be causing the issue when it gets to the error line ( https://github.com/open-AIMS/ADRIA.jl/blob/bc234aea6c4b2441e18d2c7f64ccc8d29fc56300/ext/AvizExt/viz/sensitivity.jl#L377 )

**Comment by Zapiano** [comment]
@Rosejoycrocker  @ConnectedSystems @DanTanAtAims 

I found this while migrating `src/analysis/sensitivity.jl`'s `outcome_map` to YAXArrays. I won't solve this together with the migration, since it's not related. I'm just explaining because, after the migration, we might want to test all plot functions and this one might break in this particular usecase.

**Comment by Rosejoycrocker** [comment]
PR #702 is meant to fix this, although I'll rebase and run tests because the lasat time I updated the YAXArray changes hadn't been merged yet

**Comment by Zapiano** [comment]
This was already solved.
