### ISSUE TITLE
Geospatial dataset for the Test domain does not define a valid CRS

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#800]
Hit an issue with tests failing because the [Test domain](https://github.com/open-AIMS/ADRIA.jl/tree/main/test/data/Test_domain/spatial) does not define valid CRS.

I believe in previous versions of ArchGDAL the issue was ignored. In more recent versions, relevant functions return a `NULL` value, which then causes an error to be thrown.

I'm hitting the error [here](https://github.com/open-AIMS/ADRIA.jl/blob/2d39f45d1cd7b9492b94dbc0573b3c2221b8ad52/ext/AvizExt/viz/spatial.jl#L222).

The problem file needs to be replaced.

pinging @Rosejoycrocker for awareness.

**Comment by Rosejoycrocker** [comment]
Thanks @ConnectedSystems, I'll look into it

**Comment by ConnectedSystems** [comment]
Resolved by #798 for now, but as noted, the process that creates these test files need to be updated to include a valid CRS.

**Comment by Rosejoycrocker** [comment]
@ConnectedSystems 
Note this is being addressed in some updates to the synth data repo here : https://github.com/open-AIMS/ADRIA-synthetic-data/commit/a9559e5bfa5a277a9daa0b4934cdb478e62633f2
