### ISSUE TITLE
Register v0.11.0

### ISSUE THREAD

**Issue by DanTanAtAims** [open-AIMS/ADRIA.jl#816]
@JuliaRegistrator register

Release notes:

## What's Changed
* New data package version v0.6.0.
* Fix bug where cover instead of leftover space was being used in stand alone site selection by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/610
* Add a new ten site example domain for testing by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/628
* Fix mcda method bugs  by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/629
* Fix set_factor_bounds! out of bounds for discrete factors by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/631
* Address MCDA error for single locations by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/640
* Replaces distance sorting with restrictions on the number of selected locations in the same reef by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/635
* Changes to make ADRIA precompilable under Julia v1.10 by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/646
* Update use of Makie/GeoMakie to address deprecation errors by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/647
* Add connectivity data to result set storage by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/643
* Fix larval connectivity bug by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/648
* Remove examples dir issue #584 by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/651
* Update tests for new sampling method/factor definitions by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/653
* Update factor type documentation by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/654
* Update factor types and their use by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/636
* Speed up calculation of truncated normal mean and cdf by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/652
* Add a default size for scenario plots by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/657
* CompatHelper: add new compat entry for StatsFuns at version 1, (keep existing compat) by @github-actions in https://github.com/open-AIMS/ADRIA.jl/pull/658
* CompatHelper: add new compat entry for SpecialFunctions at version 2, (keep existing compat) by @github-actions in https://github.com/open-AIMS/ADRIA.jl/pull/659
* Fix bleaching mortality  by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/660
* Clean up settler cover function to reduce confusion by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/662
* Only load up relevant RME SSP datasets by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/663
* Reset deployed-coral-risk-tol range by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/664
* Clean up scenario running methods by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/665
* Clean up use of TP matrices to align with conceptualisation of connectivity by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/667
* Support updated domain structure by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/669
* Adjustment to simulated events to address numerical errors by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/668
* Return 0 in cases where lb > ub by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/666
* Fix erroneous handling of location IDs by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/671
* Fix error in domain loading when `cluster_id` is already in string format by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/673
* Add test domain for `ReefModDomain` type by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/675
* Additional setup instructions for code style and formatting by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/676
* Fix cyclone sorting by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/683
* removed deprecate functions and function calls by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/684
* restructured documentation image directories by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/685
* Fix readjustment of number of slices bug in RSA by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/679
* Truncated normal changes by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/687
* Allow user to set whatever bounds they wish by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/688
* Switch to YAXArrays when runnin scenarios by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/690
* Remove `factors` input from `rsa()` and use scenario dataframe column names instead by @Rosejoycrocker in https://github.com/open-AIMS/ADRIA.jl/pull/696
* updated data loading test for migration to YAXArrays by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/697
* Further updates to scenario runs with MCDA by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/698
* Remove MKL from build process by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/705
* Migrate metrics.jl to YAXArrays by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/709
* Yax cube tests by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/704
* Yax viz by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/703
* Yax test update by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/700
* Remove GC workaround by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/711
* Yax migration miscellaneous by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/715
* Keep metadata in results by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/716
* CompatHelper: bump compat for DimensionalData to 0.26, (keep existing compat) by @github-actions in https://github.com/open-AIMS/ADRIA.jl/pull/714
* Finalize update of standalone MCDA methods by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/717
* Update all tests and remove NamedDims and AxisKeys from ADRIA.jl by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/718
* Validating MCDA methods and initial clean/update of tests by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/719
* Migrate from NamedDimsArrays to YAXArrays by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/695
* Provide a succinct overview of MCDA by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/720
* Add support to cyclone mortality to ReefModDomain by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/722
* Save right intervention label at ResultSet ranks YAXArray by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/724
* Hacky support for later RME reef id list by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/731
* Add support for specifying locations by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/732
* Support more vector types for maps by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/736
* Clean up connectivity and centrality methods by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/737
* Additional rank methods to determine number of locations intervened on per timestep by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/738
* Collection of miscellaneous changes by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/740
* Fix bug, min. locations to select > available locations by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/741
* CompatHelper: bump compat for DimensionalData to 0.27, (keep existing compat) by @github-actions in https://github.com/open-AIMS/ADRIA.jl/pull/744
* Connectivity viz by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/742
* Fix locations selection in ReefMod datapackage cyclone mortality loading by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/723
* Only rank locations with available area > 0 by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/734
* use provided centrality measures instead of defaults by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/751
* Improved support for spatial maps by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/750
* Repeat mention that the VS Code extension is being setup by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/748
* Convenience plotting method for connectivity/centralities by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/752
* Support plotting DHW and cyclone (mortality) scenarios by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/758
* Support deactivating environmental disturbances by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/759
* RME Result Interface by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/745
* add range to for loop by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/762
* Visualization for taxonomy cover. by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/763
* Fix erroneous function call in docstrings by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/773
* CompatHelper: bump compat for NetCDF to 0.12, (keep existing compat) by @github-actions in https://github.com/open-AIMS/ADRIA.jl/pull/765
* CompatHelper: add new compat entry for GraphMakie in [weakdeps] at version 0.5, (keep existing compat) by @github-actions in https://github.com/open-AIMS/ADRIA.jl/pull/766
* CompatHelper: add new compat entry for GeoMakie in [weakdeps] at version 0.6, (keep existing compat) by @github-actions in https://github.com/open-AIMS/ADRIA.jl/pull/767
* CompatHelper: add new compat entry for Makie in [weakdeps] at version 0.21, (keep existing compat) by @github-actions in https://github.com/open-AIMS/ADRIA.jl/pull/764
* improve load_domain docs by @arlowhite in https://github.com/open-AIMS/ADRIA.jl/pull/733
* Change assisted adaptation to a Discrete Uniform value by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/770
* Use underlying data instead of YAXArray type by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/771
* Fix mismatched function name in docstring by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/778
* Fix site_level dosctring by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/782
* Fix visualization type error by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/777
* Add methods to extract deployment location info by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/774
* Increase compression level for ResultSet by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/772
* remove breakpoint in code by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/784
* Clean up defunct dependencies by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/776
* Add default option to _sort_keys by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/787
* Assortment of improvements to SIRUS and Time Series Clustering  by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/786
* Coerce to MultiPolygon instead of Polygon by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/793
* julia-actions recommended dependabot.yml by @arlowhite in https://github.com/open-AIMS/ADRIA.jl/pull/791
* Bump julia-actions/cache from 1 to 2 by @dependabot in https://github.com/open-AIMS/ADRIA.jl/pull/795
* Bump julia-actions/setup-julia from 1 to 2 by @dependabot in https://github.com/open-AIMS/ADRIA.jl/pull/796
* Bump actions/checkout from 2 to 4 by @dependabot in https://github.com/open-AIMS/ADRIA.jl/pull/797
* Minor updates to geospatial functions/handling by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/798
* Address tests failing due to type mismatch (scenario confint) by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/801
* Fix depth min/offset being sampled for counterfactual scenarios by @ConnectedSystems in https://github.com/open-AIMS/ADRIA.jl/pull/802
* build: prototype CD integration with Provena to update model  by @PeterBaker0 in https://github.com/open-AIMS/ADRIA.jl/pull/808
* Fix broken tests by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/809
* Fix sampling test by @Zapiano in https://github.com/open-AIMS/ADRIA.jl/pull/814
* Increase release version by @DanTanAtAims in https://github.com/open-AIMS/ADRIA.jl/pull/815

## New Contributors
* @arlowhite made their first contribution in https://github.com/open-AIMS/ADRIA.jl/pull/733
* @dependabot made their first contribution in https://github.com/open-AIMS/ADRIA.jl/pull/795
* @PeterBaker0 made their first contribution in https://github.com/open-AIMS/ADRIA.jl/pull/808

**Full Changelog**: https://github.com/open-AIMS/ADRIA.jl/compare/v0.10.0...v0.11.0

**Comment by Zapiano** [comment]
@DanTanAtAims  don't forget to close this issue :)
