### ISSUE TITLE
ReefModDomain loading is not working

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#825]
When I try to load ReefModDomain:

```julia
reefmod_dom = ADRIA.load_domain(ReefModDomain, <path_to_reefmoddomain>, "45")
```

I get the following error: 

```
ERROR: ArgumentError: Can not construct YAXArray, supplied data size is (234, 3806) while axis lengths are (36, 3806)
Stacktrace:
 [1] YAXArrays.Cubes.YAXArray(axes::Tuple{…}, data::Matrix{…}, properties::Dict{…}, chunks::DiskArrays.GridChunks{…}, cleaner::Vector{…})
   @ YAXArrays.Cubes C:\Users\pribeiro\AIMS\Code\YAXArrays.jl\src\Cubes\Cubes.jl:114
 [2] YAXArray
   @ C:\Users\pribeiro\AIMS\Code\YAXArrays.jl\src\Cubes\Cubes.jl:136 [inlined]      
 [3] YAXArrays.Cubes.YAXArray(axes::Tuple{…}, data::Matrix{…})
   @ YAXArrays.Cubes C:\Users\pribeiro\AIMS\Code\YAXArrays.jl\src\Cubes\Cubes.jl:136
 [4] DataCube(data::Matrix{Float64}; kwargs::@Kwargs{species::UnitRange{Int64}, locs::Vector{String}})
   @ ADRIA c:\Users\pribeiro\AIMS\Code\ADRIA.jl\src\io\datacubes.jl:14
 [5] load_initial_cover(::Type{…}, dom_data::YAXArrays.Datasets.Dataset, site_data::DataFrames.DataFrame, loc_ids::Vector{…}, init_yr::Int64)
   @ ADRIA c:\Users\pribeiro\AIMS\Code\ADRIA.jl\src\ExtInterface\ReefMod\ReefModDomain.jl:234
``` 

What seems to be happening is that on this line https://github.com/open-AIMS/ADRIA.jl/blob/8808b0b0a13df6585213275b935f66399cdb4f36/src/ExtInterface/ReefMod/ReefModDomain.jl#L216https://github.com/open-AIMS/ADRIA.jl/blob/8808b0b0a13df6585213275b935f66399cdb4f36/src/ExtInterface/ReefMod/ReefModDomain.jl#L216

We should be doing `size_class_weights = (cdf_integral[2:end] .- cdf_integral[1:(end - 1)])`

Also, the number of size classes is hard coded (which we could avoid) and we are not ignoring the first functional group. So I this change I'm proposing won't fix everything.

**Comment by Zapiano** [comment]
@DanTanAtAims FYI

**Comment by DanTanAtAims** [comment]
This is fixed on the calibration branch, I will create a PR to main

**Comment by ConnectedSystems** [comment]
Has this issue been resolved @Zapiano @DanTanAtAims ?

**Comment by DanTanAtAims** [comment]
@ConnectedSystems @Zapiano I still need to add the fix that is on the calibration branch
