### ISSUE TITLE
CoralBlox apparent incompatibility

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#828]
We've been getting this documentation building error: https://github.com/open-AIMS/ADRIA.jl/actions/runs/10463774530/job/28976303563

![image](https://github.com/user-attachments/assets/159dc520-f20c-4802-81dc-6b3309d92985)

And today Vanessa tried to add ADRIA to her sandbox on the HPC using `]dev <path_to_ADRIA>` and she got the same error:

 
![image](https://github.com/user-attachments/assets/cf99ac2d-9778-4257-8b75-9de3d0e40c63)

I don't know what is causing this and I can't replicate this behaviour locally (when I run `]dev <path_to_ADRIA>` on my computer, everything works fine).

**Comment by ConnectedSystems** [comment]
Is this resolved now @Zapiano ?

**Comment by Zapiano** [comment]
> Is this resolved now @Zapiano ?

Yes, this was resolved.
