### ISSUE TITLE
Errors/issues in `_get_result_paths()` (C~scape interface)

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#856]
When loading C~scape data, there is a direct error message used when it fails to any netcdfs.

This causes an error as it uses a variable `res_subdir`, which does not exist

https://github.com/open-AIMS/ADRIA.jl/blob/899bbc9d7654e49a78fa8257d407a43cf38b07f0/src/io/cscape_result_io.jl#L547-L560

The are two other unrelated issues in this function:

1. Using `error()` directly is bad practice.
    Pick a more appropriate one from [this list](https://docs.julialang.org/en/v1/manual/control-flow/#Built-in-Exceptions)
    
    I would suggest ArgumentError, as the error likely stems from the user providing the wrong directory:
    `throw(ArgumentError("some message))"`
    
2. There is a closing double quote missing in the docstring (`"NetCDF_Scn.*.nc`)

A further question is whether the `r` preceeding the search haystack is necessary (e.g., `r"NetCDF_Scn.*.nc"`)

**Comment by DanTanAtAims** [comment]
I tried to remove the preceeding `r` and it no longer treats the string as a regex.

**Comment by ConnectedSystems** [comment]
Oh, reflex, okay nevermind me
